### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by threat** [redecentralize/organize#1]
Delete

**Comment by cjduncana** [comment]
I just recently discovered [Gitter](https://gitter.im). Is there a redecentralize channel?

**Comment by frabcus** [comment]
There isn't.

We do have a Slack channel that was used  to organize the conference,
but has gone totally quiet now.

What kind of thing do you want to use Gitter for? Would it be a public,
just click to join channel or something more private?

I've never used Gitter, so I'm not sure what culture around it is!

Francis

On Wed, 11 Nov 2015, at 10:42 AM, Christopher John Duncan Araúz wrote:

> I just recently discovered Gitter[1]. Is there a redecentralize
> channel?
> 
> — Reply to this email directly or view it on GitHub[2].

Links:
1. https://gitter.im
2. https://github.com/redecentralize/swarm/issues/1#issuecomment-155731338

**Comment by ThreaT** [comment]
Is this organization dead now?

**Comment by cjduncana** [comment]
@frabcus The developers that lead the repository creates channels in Gitter that can either be private or public. The only credential needed is a GitHub account.

**Comment by cjduncana** [comment]
@ThreaT Redecentralize has been heavy communicating in the [mailing list](https://github.com/redecentralize/swarm/wiki/Email-list), but had gone silent for the past month.

**Comment by madduck** [comment]
whoever made this channel, if you want `matrix.org` integration (for true decentralization, because IRC is not…) then everyone needs to `/part` temporarily so the channel can be registered.
